app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref='role', lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

models/book.py
class Book:
    '''
    Movie class to define Movie Objects
    '''

    def __init__(self,id,title,author,poster,publisher,publishedDate):
        self.id =id
        self.title = title
        self.author=author
        # self.poster = 'http://books.google.com/books/content?id=_oG_iTxP1pIC&printsec=frontcover&img=1&zoom=5&source=gbs_api'+ poster
        self.publisher= publisher
        self.publishedDate=publishedDate

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError
from wtforms.validators import Required,Email
from ..models import User


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_sqlalchemy import SQLAlchemy
from config import DevConfig
from flask_uploads import UploadSet,configure_uploads,IMAGES

#from config import config_options


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)
simple = SimpleMDE()


app = Flask(__name__, instance_relative_config=True)


# Setting up configuration
app.config.from_object(DevConfig)

# Initializing flask extensions
bootstrap.init_app(app)
db.init_app(app)
login_manager.init_app(app)
mail.init_app(app)
simple.init_app(app)


# Registering the blueprint
from .main import main as main_blueprint
app.register_blueprint(main_blueprint)

from .auth import auth as auth_blueprint
app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

from app import views


if __name__ == '__main__':
    app.run()

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required

from ..models import User
from . import main
from .forms import UpdateProfile
from .. import db, photos
import cloudinary
import cloudinary.uploader
from cloudinary.uploader import upload
import cloudinary.api
from cloudinary.utils import cloudinary_url
from ..request import  get_book

@main.route('/', methods = ['GET','POST'])
def index():
    title = 'Popular Books'
    book = get_book()
    return render_template('index.html', title=title, books=book)

@main.route('/user/<uname>', methods = ['GET','POST'])
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

    return render_template("profile/profile.html", user = user, form=form)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = request.files['photo']
        upload = cloudinary.uploader.upload(filename)
        path = upload.get('url')
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/views.py
from flask import render_template
from app import app
from .request import  get_book

# Views
@app.route('/')
def index():
    '''
    Root function returning index/home page with data
    '''
    book= get_book()
    title = 'title'
    
    return render_template('index.html',books=book, title=title)
@app.route('/book/<int:id>')
def get_books(id):

    '''
    View book page function that returns the movie details page and its data
    '''
    book= get_books(id)
    title = f'{book.title}'

    return render_template('book.html',title=title,book=book)

app/templates/base.html
{% block doc -%}
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {% include 'navbar.html' %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/book.html
<!-- {% extends 'base.html'%} {% import 'macros.html' as macro%} {% block content %}
<div class="container">

    
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 posterPath" style="background: url({{book.poster}}) no-repeat center center">
        </div>

        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 book-details">
            <h3>{{ book.title }}</h3>

            <p class="publisher"> {{ book.publisher }}</p>
            <p class="ratings"> <b> {{ book.vote_average }}</b> - <i>{{ book.vote_count}} votes </i> </p>


        </div>
    </div>

</div>
{% endblock %} -->

app/templates/fourOwfour.html
{% extends 'base.html'%} {% block content %}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
 {% extends 'base.html'%} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %}
<body>
    {% block content %}
    <h3 style="text-align:center"> {{title}}</h3>

        <div style="text-align:center">
        <div class="row">
        {%for image,book_title, author in books%}
        <div class="col-md-4 p-3">
        <div class = "card">
        <div>
        <img class="card-image" style="width:40%;text-align:center" src="{{image}} ">
        </div>
        <div class="card-body">
        <h5 class="card-title">{{book_title}}</h5>
        <p class="card-text"> Author: {{author}}</p>
        <a href="#" class="btn btn-primary">View Book</a>
        </div>
        </div>
        </div>
        {%endfor%}
         </div>
    {% endblock%}
</body>

app/templates/navbar.html
<div class="navigation">
<div class="navbar navbar-default" role="navigation">

    <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Profile</a></li>
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
    </ul>
</div>
</div>

app/templates/new_review.html
<!-- {% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container">

    <div class="col-md-8">

        <img src="{{book.poster}}" alt="{{book.title}}" class="img-responsive">
    </div>

    <div class="col-md-4">

        {{ wtf.quick_form(review_form) }}
    </div>

</div>

{% endblock %} -->

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}

            <img src="{{user.profile_pic_path}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>

            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input class="btn btn-primary" type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>

<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}